name: Spring Boot CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env: 
 JAVA_VERSION: '17'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK with  ${{env.JAVA_VERSION}}
      uses: actions/setup-java@v4
      with:
        java-version: ${{env.JAVA_VERSION}}
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn clean package --file pom.xml
    
    - name: Run tests
      run: mvn test
    
    - name: Upload JAR
      uses: actions/upload-artifact@v4
      id: artifact-upload-step
      with:
        name: application
        path: target/*.jar
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    
    steps:
    - name: Download JAR
      uses: actions/download-artifact@v4
      with:
        name: application
        run:  |
          echo "Listing downloaded artifacts:"
          ls -R .