name: Spring Boot CI 

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  id-token: write
  contents: read

env:
  AZURE_WEBAPP_NAME: my-springboot-app    # Set to your Azure App Service name
  JAVA_VERSION: '21'                      # Set to your Java version
  DISTRIBUTION: 'temurin'                 # Set to your Java distribution

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: ${{ env.DISTRIBUTION }}
        cache: maven
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Run tests
      run: mvn test
    
    - name: Upload JAR
      uses: actions/upload-artifact@v4
      with:
        name: application
        path: target/*.jar
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    
    steps:
    - name: Download JAR
      uses: actions/download-artifact@v4
      with:
        name: application
        run:  |
          echo "Listing downloaded artifacts:"
          ls -R .